Form/DataTransformer/EntityToIdTransformer.php
<?php

namespace Anacona16\Bundle\DependentFormsBundle\Form\DataTransformer;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\InvalidConfigurationException;
use Symfony\Component\Form\Exception\UnexpectedTypeException;
use Symfony\Component\Form\Exception\TransformationFailedException;

class EntityToIdTransformer implements DataTransformerInterface
{
    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;

    /**
     * @var string
     */
    protected $class;

    /**
     * @var \Doctrine\ORM\UnitOfWork
     */
    protected $unitOfWork;

    /**
     * @param EntityManagerInterface    $entityManager
     * @param string                    $class
     */
    public function __construct(EntityManagerInterface $entityManager, $class)
    {
        $this->entityManager = $entityManager;
        $this->class = $class;
        $this->unitOfWork = $this->entityManager->getUnitOfWork();
    }

    /**
     * Transforms an object to a string (number).
     *
     * @param mixed $entity
     *
     * @return string
     */
    public function transform($entity)
    {
        if (null === $entity || '' === $entity) {
            return 'null';
        }

        if (!is_object($entity)) {
            throw new UnexpectedTypeException($entity, 'object');
        }
        
        if (!$this->unitOfWork->isInIdentityMap($entity)) {
            throw new InvalidConfigurationException('Entities passed to the choice field must be managed');
        }

        return $entity->getId();
    }

    /**
     * Transforms a string (number) to an object.
     *
     * @param mixed $id
     *
     * @return mixed|void
     *
     * @throws TransformationFailedException if object is not found
     */
    public function reverseTransform($id)
    {
        if ('' === $id || null === $id) {
            return;
        }

        if (!is_numeric($id)) {
            throw new UnexpectedTypeException($id, 'numeric'.$id);
        }

        $entity = $this->entityManager->getRepository($this->class)->findOneById($id);

        if ($entity === null) {
            throw new TransformationFailedException(sprintf('The entity with key "%s" could not be found', $id));
        }

        return $entity;
    }
}

Form/Type/DependentFormsType.php
<?php

namespace Anacona16\Bundle\DependentFormsBundle\Form\Type;

use Anacona16\Bundle\DependentFormsBundle\Form\DataTransformer\EntityToIdTransformer;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DependentFormsType extends AbstractType
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @var array
     */
    private $dependentForms;

    /**
     * @param EntityManagerInterface    $entityManager
     * @param array                     $dependentForms
     */
    public function __construct(EntityManagerInterface $entityManager, $dependentForms)
    {
        $this->entityManager = $entityManager;
        $this->dependentForms = $dependentForms;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'empty_value' => '',
            'entity_alias' => null,
            'parent_field' => null,
            'show_loading' => true,
            'compound' => false,
        ));
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $entities = $this->dependentForms;

        $options['class'] = $entities[$options['entity_alias']]['class'];
        $options['property'] = $entities[$options['entity_alias']]['property'];

        $options['no_result_msg'] = $entities[$options['entity_alias']]['no_result_msg'];

        $builder->addViewTransformer(new EntityToIdTransformer(
            $this->entityManager,
            $options['class']
        ), true);

        $builder->setAttribute('parent_field', $options['parent_field']);
        $builder->setAttribute('entity_alias', $options['entity_alias']);
        $builder->setAttribute('no_result_msg', $options['no_result_msg']);
        $builder->setAttribute('show_loading', $options['show_loading']);
        $builder->setAttribute('empty_value', $options['empty_value']);
    }

    /**
     * @param FormView      $view
     * @param FormInterface $form
     * @param array         $options
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['parent_field'] = $form->getConfig()->getAttribute('parent_field');
        $view->vars['entity_alias'] = $form->getConfig()->getAttribute('entity_alias');
        $view->vars['no_result_msg'] = $form->getConfig()->getAttribute('no_result_msg');
        $view->vars['show_loading'] = $form->getConfig()->getAttribute('show_loading');
        $view->vars['empty_value'] = $form->getConfig()->getAttribute('empty_value');
    }

    public function getParent()
    {
        return FormType::class;
    }
}

Controller/DependentFormsController.php
<?php

namespace Anacona16\Bundle\DependentFormsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\Translation\TranslatorInterface;

class DependentFormsController extends AbstractController
{
    /**
     * This action handler the ajax call for a dependent field type.
     *
     * @param Request $request
     * @param TranslatorInterface $translator
     *
     * @return Response
     */
    public function getOptionsAction(Request $request, TranslatorInterface $translator)
    {
        $entityAlias = $request->request->get('entity_alias');
        $parentId = $request->request->get('parent_id');
        $emptyValue = $request->request->get('empty_value');

        $entities = $this->getParameter('anacona16.dependent_forms_config');
        $entityInformation = $entities[$entityAlias];

        if ($entityInformation['role'] !== 'IS_AUTHENTICATED_ANONYMOUSLY') {
            $this->denyAccessUnlessGranted($entityInformation['role']);
        }
        if( '' !== $parentId){

        $qb = $this->getDoctrine()
            ->getRepository($entityInformation['class'])
            ->createQueryBuilder('e')
            ->where('e.'.$entityInformation['parent_property'].' = :parent_id')
            ->orderBy('e.'.$entityInformation['order_property'], $entityInformation['order_direction'])
            ->setParameter('parent_id', $parentId)
        ;

        if (null !== $entityInformation['callback']) {
            $repository = $qb->getEntityManager()->getRepository($entityInformation['class']);

            if (!method_exists($repository, $entityInformation['callback'])) {
                throw new \InvalidArgumentException(sprintf('Callback function "%s" in Repository "%s" does not exist.', $entityInformation['callback'], get_class($repository)));
            }

            $repository->$entityInformation['callback']($qb);
        }

        $results = $qb->getQuery()->getResult();
        }

        if (empty($results)) {
            return new Response('<option value="">'.$translator->trans($entityInformation['no_result_msg']).'</option>');
        }

        $html = '';
        if ($emptyValue !== false) {
            $html .= '<option value="">'.$translator->trans($emptyValue).'</option>';
        }

        $propertyAccessor = PropertyAccess::createPropertyAccessor();

        foreach ($results as $result) {
            if ($entityInformation['property']) {
                $resultString = $propertyAccessor->getValue($result, $entityInformation['property']);
            } else {
                $resultString = (string) $result;
            }

            $html .= sprintf('<option value="%s">%s</option>', $result->getId(), $resultString);
        }

        return new Response($html);
    }
}

Resources/views/Form/fields.html.twig
{% block dependent_forms_widget %}

    <select {{ block('widget_attributes') }}></select>

    {% if show_loading %}
        <img src="{{ asset('bundles/dependentforms/images/ajax-loader.gif' ) }}" id="dependent_forms_loader" style="display: none;">
    {% endif %}
    <script type="text/javascript">
        jQuery(function () {
            jQuery("select#{{ form.parent.offsetGet( parent_field ).vars.id }}").change(function () {
                var selected_index = {{ value ? value : 0 }};
                jQuery("#dependent_forms_loader").show();
                jQuery.ajax({
                    type: "POST",
                    data: {
                        parent_id: jQuery(this).val(),
                        entity_alias: "{{ entity_alias }}",
                        empty_value: "{{ empty_value }}"
                    },
                    url: "{{ path('anacona16_dependent_forms') }}",
                    success: function (msg) {
                        if (msg != '') {
                            jQuery("select#{{ form.vars.id }}").html(msg).show();
                            jQuery.each(jQuery("select#{{ form.vars.id }} option"), function (index, option) {
                                if (jQuery(option).val() == selected_index)
                                    jQuery(option).prop('selected', true);
                            });
                            jQuery("select#{{ form.vars.id }}").trigger('change');
                            jQuery("#dependent_forms_loader").hide();
                        } else {
                            jQuery("select#{{ form.vars.id }}").html('<em>{{ no_result_msg|trans() }}</em>');
                            jQuery("#dependent_forms_loader").hide();
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        jQuery('html').html(xhr.responseText);
                    }
                });
            });
            jQuery("select#{{ form.parent.offsetGet( parent_field ).vars.id }}").trigger('change');
        });
    </script>

{% endblock %}